# -*- coding: utf-8 -*-
"""creditcard fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNgUKchHiGSEVpzJeN_7_SldycJzaER8

# **Credit Card Fraud Detection Using Machine Learning**

## Dataset Overview

- Total Transactions: 284,807
- Total Features: 31
- Fraud Transactions: 492
- Normal Transactions: 284,315

Target Variable:
- 0 = Legitimate Transaction
- 1 = Fraudulent Transaction
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

df = pd.read_csv("creditcard.csv")

print(df.shape)
df.head()

print(df.info())

"""## Exploratory Data Analysis

### Key Findings

- No missing values were found.
- Dataset is highly imbalanced.
- Fraudulent transactions account for approximately 0.17% of all transactions.
"""

print(df['Class'].value_counts())

df['Class'].value_counts().plot(kind='bar')

plt.title('Fraud vs Normal Transactions')
plt.xlabel('Class')
plt.ylabel('Count')

plt.show()

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, lr_pred))
print("Precision:", precision_score(y_test, lr_pred))
print("Recall:", recall_score(y_test, lr_pred))
print("F1 Score:", f1_score(y_test, lr_pred))

rf = RandomForestClassifier(
    n_estimators=50,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall:", recall_score(y_test, rf_pred))
print("F1 Score:", f1_score(y_test, rf_pred))

cm = confusion_matrix(y_test, rf_pred)
print(cm)

import matplotlib.pyplot as plt

plt.figure(figsize=(5,4))
plt.imshow(cm)

plt.colorbar()

plt.xticks([0,1], ['Normal','Fraud'])
plt.yticks([0,1], ['Normal','Fraud'])

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Random Forest Confusion Matrix')

for i in range(2):
    for j in range(2):
        plt.text(j, i, str(cm[i, j]), ha='center', va='center')

plt.show()

"""## Results

| Metric | Logistic Regression | Random Forest |
|----------|----------|----------|
| Accuracy | 99.89% | 99.95% |
| Precision | 82.76% | 97.37% |
| Recall | 48.98% | 75.51% |
| F1 Score | 61.54% | 85.06% |

Two machine learning models were evaluated for fraud detection: Logistic Regression and Random Forest. Due to the highly imbalanced nature of the dataset, evaluation focused on precision, recall, and F1 score rather than accuracy alone. Random Forest significantly outperformed Logistic Regression, achieving higher precision, recall, and F1 score. Therefore, Random Forest was selected as the preferred model for detecting fraudulent transactions.## Conclusion

Random Forest outperformed Logistic Regression across all evaluation metrics.

The model achieved:

- Precision: 97.37%
- Recall: 75.51%
- F1 Score: 85.06%

Random Forest was selected as the final model because it identified fraudulent transactions more effectively.
"""
